### ISSUE TITLE
Proposal: Apache Avro toolkit for SerDe

### ISSUE THREAD

**Issue by fketelaars** [IBMStreams/administration#102]
[Apache Avro](https://avro.apache.org/docs/1.8.1/index.html) is a popular format for serializing messages with variable columns and evolving structures. Proposing toolkit to serialize a tuple to Avro format and deserialize from Avro to a Streams tuple. Avro supports multiple languages, among other C++ and Java. Initially proposing to create a toolkit in Java with 2 main operators: AvroToTuple and TupleToAvro.

**Comment by mikespicer** [comment]
+1
I believe you have seen the AVRO operators in the storm benchmark which may or may not be useful https://github.com/IBMStreams/benchmarks/tree/master/StreamsAvroOperators

**Comment by chanskw** [comment]
+1 

@mikespicer I have previously looked at the Avro operators before to try to pull that out.  But those operators seem very specific to the email benchmark. I think we need something more generic.

**Comment by mikespicer** [comment]
@chanskw OK, I did not look at them closely but its not surprising that they were implemented for the specific needs of the benchmark and not made to be generic.

**Comment by chanskw** [comment]
@fketelaars are you the only committer to this project?  Who else should be committer ?

**Comment by fketelaars** [comment]
Please add @jchailloux as well

**Comment by chanskw** [comment]
Done!

**Comment by fketelaars** [comment]
Thanks!
 
Best regards, Vriendelijke groet,
 
Frank Ketelaars
IBM Analytics
Big Data Technical Leader - Europe
 
Phone: 31-653 243 092
E-mail: fketelaars@nl.ibm.com
 
Sent through IBM Verse
 
 
----- Original message -----From: Samantha Chan <notifications@github.com>To: IBMStreams/administration <administration@noreply.github.com>Cc: Frank Ketelaars/Netherlands/IBM@IBMNL, Mention <mention@noreply.github.com>Subject: Re: [IBMStreams/administration] Proposal: Apache Avro toolkit for SerDe (#102)Date: Thu, Dec 8, 2016 4:02 PM 
Done!
—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

 Tenzij hierboven anders aangegeven: / Unless stated otherwise above:
IBM Nederland B.V.
Gevestigd te Amsterdam
Inschrijving Handelsregister Amsterdam Nr. 33054214
