### ISSUE TITLE
Provide description for native language support

### ISSUE THREAD

**Issue by ZollnaPa** [IBMStreams/administration#105]
After a discussion about the NLS, @chanskw suggested to provide the process description, how to handle NL support. The wiki in this project would be the correct location.

**Comment by chanskw** [comment]
@ZollnaPa I have assigned this to you.  Can you please add the documentation so we can see how NLS was implemented in all the toolkits and make sure that it can be updated correctly going forward?

**Comment by ZollnaPa** [comment]
I started the work...

**Comment by ZollnaPa** [comment]
@chanskw Please review the description and give me a feedback. This description is the rough collection of information how to implement the messages in the toolkits. From my point of view, you should understand how to implement the message bundles by reading this guide. If you have some questions or issues to understand the process, then let me know, I'll try to improve the description.

**Comment by ZollnaPa** [comment]
The link to https://github.com/IBMStreams/administration/wiki/The-messages-and-the-NLS-for-toolkits is included to the README.md of all toolkits that are part of the product, now.

**Comment by jakrmpotic** [comment]
@ZollnaPa I made some copy edits to the topic - I hope that helps!

**Comment by ZollnaPa** [comment]
@jakrmpotic Yes,it helps. I just corrected the links to the wiki page in the topology toolkit and other that use the page as a reference. By renaming of the md-file on wiki, the link to the page changes.
The correct link: [Messages and National Language Support for toolkits](https://github.com/IBMStreams/administration/wiki/**Messages-and-National-Language-Support-for-toolkits**)
