### ISSUE TITLE
Separate individual resource managers out from one repository

### ISSUE THREAD

**Issue by bmwilli** [IBMStreams/administration#107]
I am working on the Mesos Resource Manager for IBM Streams.  I do not believe it should be in the same repository as the YARN resource manager.  They should be developed, tested, and versioned independently. If there is a way to keep them related under a resource managers group that would be fine.

**Comment by chanskw** [comment]
@bmwilli are you proposing that you would like to start a new repository for Mesos Resource Manager work?  

To do this, I suggest we do the following:
1.  streamsx.resourceManagers project should be renamed to streamsx.yarn
2.  we will create a new repository called streamsx.mesos for your Mesos Resource manager work.

Is this a good approach?

**Comment by bmwilli** [comment]
I think that would be great.  Thanks!!

**Comment by mikespicer** [comment]
+1 to having a new repo for the mesos resource manager.  From experience with the messaging toolkit it can prove problematic to group together similar functionality that is being developed at different rates or relies on technologies that are changing at different rates. In hindsight it would have been better to have the YARN resource manager be in a repo only intended for a YARN resource manager implementation rather than a generic resource manager repo for all resource manager implementations.

**Comment by schulz2** [comment]
This might be trivial, but would it be possible to have something like
streamsx.resourceManagers.yarn
streamsx.resourceManagers.mesos

**Comment by bmwilli** [comment]
Just curious what is the process / schedule to proceed?

**Comment by chanskw** [comment]
I will get to this and create a repo for you tomorrow.  Sorry for the delay!

**Comment by chanskw** [comment]
@bmwilli who will be a committer to the mesos project?

I do not think you have signed the Github CLA agreement.  If so, can you please sign this agreement here:  https://github.com/IBMStreams/administration/blob/master/IBMStreams-cla-individual.pdf

Please send a soft copy to me and @petenicholls.  Please also send the hard copy of the agreement to Pete as stated in the agreement.  I will create the repository and make you a committer once I have received the agreement.

**Comment by chanskw** [comment]
+1

**Comment by bmwilli** [comment]
Thanks.  I have sent the agreement to you.  In addition I sent the hard copy to Pete a few days ago.

**Comment by chanskw** [comment]
Created repository and @bmwilli  is committer to project.  I did not rename the Yarn resource manager project yet.  I need to check if there is any dependency to that project before I can rename it.

**Comment by bmwilli** [comment]
Thank you.
