### ISSUE TITLE
Proposal: new project streamsx.geospatialext

### ISSUE THREAD

**Issue by ulemanstreaming** [IBMStreams/administration#108]
I've started to build up a toolkit with geospatial functionality that I need for various projects. Several of these functions and operators have general applicability; some of them I consider "missing" functionality in the supported streams.geospatial toolkit. Examples are a polygon orienter to enforce our round-earth rules for ring orientation on data coming from flat-earth sources and various parsers and formatters for GeoJSON.

So far I've been able to create my extensions strictly in SPL only, by combining pieces already in the streams.geospatial toolkit. My goals are 1) to build reusable components that I happen to need; 2) to show how geospatial functions and operators can be used to create new functionality; and 3) to serve as a sort of requirements and design spec for future inclusion of some of these features in streams.geospatial (probably reimplemented as primitive operators and native functions). My goals do not include optimized performance or elegance, which is why, for example, I consider text string manipulation of WKT geometries acceptable.

I thought of several possible names for such a toolkit: streamsx.geospatial (confusing with streams.geospatial?), streamsx.geospatialextras (too informal?), streamsx.geospatialextensions (too long?), and streamsx.geospatialext (too vague?). I'm totally open to suggestions or being overruled.

**Comment by ddebrunner** [comment]
There is an empty location based services project:

https://github.com/IBMStreams/streamsx.locationbasedservices

**Comment by chanskw** [comment]
I forgot about the locationbasedservices.  We can definitely use this to host these geospatial functions.

**Comment by ddebrunner** [comment]
In the interest of a short name maybe `streamsx.geoext` with the SPL namespace being `com.ibm.streamsx.geoext`. Short for geospatial extensions. 

I thin we either create a new repo and delete `locationbasedservices` or rename it.

**Comment by ulemanstreaming** [comment]
I like streamsx.geoext. 

I can see using a locationbasedservices repo for other things that are more use case- or solution-oriented than the more basic functionality I have for geoext. For example, my weather geofencing sample, combining weather data (and the streamsx.weather toolkit) and geospatial stuff (from streams.geospatial and streamsx.geoext) could fit there (though it could also go into the general samples repo). But if it's currently empty, removing or renaming it is fine.

**Comment by mikespicer** [comment]
+1 for streamsx.geoext

**Comment by chanskw** [comment]
I will create this repo later this week.

**Comment by chanskw** [comment]
Converted locationbasedservices to geoext.
