### ISSUE TITLE
create a new project for face detection and recognition sample that uses Edgent, OpenCV, WIoTP, Streams

### ISSUE THREAD

**Issue by dlaboss** [IBMStreams/administration#109]
Work is ongoing on a sample/demo that includes Edgent, OpenCV, WIoTP and Streams.
We would like to be able to make the source openly available.  Maybe under a repo named "sample.faceRecognition" or such.

The purpose is to demonstrate the possible... an end-to-end use of these components and provide others with code they could learn from and perhaps build upon.  The image processing will probably be rather simplistic.

**Comment by chanskw** [comment]
Can you elaborate on what use case the sample is for?  For it to be a new project, I think we need a bigger end-to-end sample that can be used as a starter kit, similar to the water conservation starter kit.  If we are going to create a project, what would this starter kit be called?  Would it be as elaborate as the water conservation app, where we will have capabilities for easily deploying the application to Bluemix?

If this is not going to be such a big sample, would hosting it in here work for now:  https://github.com/IBMStreams/samples

And when it becomes more well defined, then we can create a separate starter kit repository for it?

**Comment by dlaboss** [comment]
A suggestion for the repo name:  edgeVideoAnalytics.starterKit  (prefaced with streamsx like the streamsx.waterConservation.starterKit?)

Video Analytics at the Edge Starter Kit - An end-to-end video analytic demonstration system consisting of an Apache Edgent based smart camera IoT device performing general face detection, and an IBM Streams application performing specific face recognition.

**Comment by chanskw** [comment]
+1

I suggest calling it streamsx.edgevideoanalytics.starterkit.  

I am going to keep voting until tomorrow at 9 am and will create repository if there is no objection.

Thanks!

**Comment by mikespicer** [comment]
+1

**Comment by chanskw** [comment]
@dlaboss who should be a committer other than yourself?

**Comment by chanskw** [comment]
Done.  Please let me know who else too add and I will add.

**Comment by dlaboss** [comment]
@chanskw Thanks!  Please add Jerome Chailloux (jchailloux).
