### ISSUE TITLE
Discussion: new project streamsx.objectstorage

### ISSUE THREAD

**Issue by markheger** [IBMStreams/administration#110]
The Bluemix Object Storage service provides a solution for getting files onto the cloud for Streams application.
This blog describes the way to achieve this and provides a sample application:
https://www.ibm.com/blogs/bluemix/2016/02/leverage-object-storage-for-streaming-analytics/

But there are additional scenarios that need to be covered:
- Identifying new files or file changes in Object Storage
- Storing a file in Object Storage
- Move or remove a file Object Storage

I would like to gather the code being done by several teams in a single toolkit that will be published on github.com/IBMStreams.

My proposal is to create a new repository streamsx.objectstorage, where we can discuss about the requirements and later deliver the toolkit code.

**Comment by chanskw** [comment]
+1

**Comment by mikespicer** [comment]
+1

**Comment by chanskw** [comment]
Who would be the initial committers to this new repository?

**Comment by chanskw** [comment]
streamsx.objectstorage created.  Please let me know if you need to add more committers.
