### ISSUE TITLE
Proposal: streamsx.slack repo to support integration with Slack

### ISSUE THREAD

**Issue by nelsonong** [IBMStreams/administration#115]
# Introduction
Slack is a cloud-based set of team collaboration tools used for real-time messaging, archiving and search. It is commonly used in corporate/team settings (such as IBM) to bring communication between teams into one place.

Slack has a full directory of apps that can be found [here](https://slack.com/apps). These apps can easily be created using Slack's provided [API](https://api.slack.com/) and integrated with IBM Streams.

One such app is [Incoming WebHooks](https://slack.com/apps) which allows users to specify a Slack channel and receive an associated WebHook URL. Messages sent to this URL are redirected to the associated Slack channel.

# Proposal
I would like to propose that a new repository and toolkit be created to enable application developers to perform various operations with their Slack environments (through integration with available apps/API).

One such operation would be to send messages/alerts from streams applications to Slack channels.

I propose that the repository be called **streamsx.slack** and the toolkit be called **com.ibm.streamsx.slack**.

# Initial contribution
The toolkit will initially contain a *SendSlackMessage* operator that will ingest tuples and output messages to a specified WebHook URL.

The parameters for the *SendSlackMessage* operator are as follows:
- **slackUrl (required)**: Slack WebHook URL to send alert to.
- **username**: Username to display for message (default: "SendSlackMessage").
- **iconUrl**: Image to display for message's icon (default: IBM Streams logo).
- **messageAttribute**: The incoming tuple attribute to use as content for the outgoing message (default: "message").

**Comment by mikespicer** [comment]
+1 for toolkit

**Comment by chanskw** [comment]
+1

**Comment by ddebrunner** [comment]
+1

More for discussion in the toolkit but having the ability to set the username/icon from the tuple would be useful. E.g. the ability to have different icons based upon severity of the alert.

Maybe even the URL as well to be set from the tuple.

**Comment by ddebrunner** [comment]
I think the incoming webhooks link was meant to be:

**Comment by chanskw** [comment]
repository created
