### ISSUE TITLE
Proposal: Repository to hold jmx client applications

### ISSUE THREAD

**Issue by bmwilli** [IBMStreams/administration#121]
I have developed two Streams JMX Client applications that use the JMX API.  I would like to contribute them to streamsx.  They are not toolkits, they are java applications meant to be used outside of a streams cluster.

The first is a Metrics and Status cache that is used by my customer.  It provides a cache of metrics and status pulled from a streams instance, and presents a REST endpoint to retrieve.  The key reason we have this utility is to shield Streams from clients that request metrics and status on individual jobs at a high rate.  We found this can cause performance issues.  By caching the metrics using a single call to get all metrics for an instance, we can provide job level requests, but with less JMX chatter with the Streams JMX server.

The second is a command line tool similar to streamtool, however, using the JMX API, it allows the client to be run from hosts where Streams is not installed.

I propose a new repository be created for these and possibly other JMX based clients and samples.

Possible names are:

streamsx.jmx
streamsx.jmxclients

I am leaning toward streamsx.jmxclients to be clear.

Thoughts?

Thanks,
Brian Williams

**Comment by mikespicer** [comment]
I like the notion of having clients or apps in the name to make it clear that its utility types of apps rather than a toolkit of operators.

**Comment by ddebrunner** [comment]
I like the `streamsx.jmxclients` name, `streamsx.jmx` would be a good name for a JMX SPL toolkit.

**Comment by bmwilli** [comment]
streamsx.jmxclients works well.  What is the next step in the process?  Can we get the repo created?

**Comment by bmwilli** [comment]
It has been almost 3 weeks since I requested this, and no further discussion.  How do we proceed?

**Comment by mikespicer** [comment]
+1 to streamsx.jmxclients

**Comment by petenicholls** [comment]
back from vacation....creating repos streamsx.jmxclients anbd closing this issue.

**Comment by petenicholls** [comment]
all set up and ready to go
