### ISSUE TITLE
Proposal: streamsx.openwhisk repository for integration with OpenWhisk

### ISSUE THREAD

**Issue by sadekjb** [IBMStreams/administration#123]
We would like to propose a repository for integration support between IBM Streams and OpenWhisk,
the repository will be the place for discussing the use case scenarios and requirements and for developing a toolkit. 

The toolkit developments will include operators and sample applications for the OpenWhisk and Streams integration common use cases, such as invoking actions and triggers on the Bluemix OpenWhisk service from Streams flow.

The code will use the streamsx.inet toolkit operators and functions.

**Comment by mikespicer** [comment]
+1

**Comment by petenicholls** [comment]
+1

**Comment by petenicholls** [comment]
Creating initial repos in order for the discussion to move there regarding use cases and requirements.

Calling repos streamsx.OpenWhisk for now.  Depending on the use case and resultant content name may change to better reflect contents.

**Comment by petenicholls** [comment]
Please move further discussion to streamsx.OpenWhisk
