### ISSUE TITLE
Proposal for new streamsx.iot.starter

### ISSUE THREAD

**Issue by natashadsilva** [IBMStreams/administration#125]
The [Water conservation starter kit])https://github.com/natashadsilva/streamsx.waterConservation.starterKit/) is a complete sample application demonstrating the Streams/Edgent/Weather application. It has  a one-click deployment that  handles all the setup steps needed to create Streams applications that analyze data from IoT devices.  

The goal of this proposal is to create a simplified version of the water conservation starter kit.  It has a one-click deploy that will create the needed services and credentials. Right now, it performs steps 1-3 of the [manual steps](https://developer.ibm.com/streamsdev/docs/setup-instructions-connecting-edgent-streams-applications-watson-iot-platform/) in the link above, but does not deploy any jobs because the user might incur a cost. 

Although the setup steps can be done manually and are not difficult, there are quite a few things to do, which could be discouraging.

The initial commit creates a landing page with links to available tutorials and all the needed credentials.   This way, if someone is following a tutorial or recipe, then he/she can deploy the services and then continue with the tutorial.  

This could be a branch in the samples repository but I think making it its own repository is cleaner and easier to find.  
If the proposal is accepted we'll update the starter kits link on http://ibmstreams.github.io/ to include it.

[Sample landing page](http://streams-iot-starter.mybluemix.net/) 
Repo: https://github.com/natashadsilva/streamsx.iot.starter

Please vote.

**Comment by chanskw** [comment]
+1  This is an interesting way to get people started.  
I find the tutorial flow a little confusing.  Perhaps a diagram will help.  But we can work on that a bit later.

I think this is a great way to build starter kit for streams.  Another useful starter kit, maybe to show people how to deploy message hub and streams.. and getting data from there.

**Comment by chanskw** [comment]
I will leave this open for until next Wednesday Oct 11.  Please vote or let us know if you have any objection.  Thanks!

**Comment by chanskw** [comment]
@natashadsilva can we call this streamsx.iot.starterKit?
 
So the name matches with other starter kit?

**Comment by natashadsilva** [comment]
@chanskw I went with just starter and not starter kit because it doesn't have a whole application, which most other starter kits do have; not sure if that difference is worth using a slightly different name ?

**Comment by ddebrunner** [comment]
Could it be just a sample then in the `streamsx.iot` toolkit?

**Comment by chanskw** [comment]
I thought about the same thing.. whether it can be part of streamsx.iot.... But this is actually a starter kit that people can customize after it is launched in Bluemix I think.

**Comment by chanskw** [comment]
I propose to keep starterKit in the name and not make this distinction.

@natashadsilva in the generated *.properties file, I think it's missing an equal sign in apiToken.  This is what got generated for me:

org=myorg
apiKey=mykey
apiTokenmytoken

**Comment by chanskw** [comment]
@ddebrunner do you have any objection to this?  I tried this out and it is very helpful.  I think having a top level starter kit is a good idea here as it provides more visibility.  We can link to the starter kit from streamsx.iot.  Please let me know.

**Comment by ddebrunner** [comment]
+1

**Comment by mikespicer** [comment]
+1

**Comment by chanskw** [comment]
Repository streamsx.iot.starterkit is created.
