### ISSUE TITLE
Proposal:  streamsx.microservice

### ISSUE THREAD

**Issue by chanskw** [IBMStreams/administration#126]
I am proposing the creation of the streamsx.microservice repository.  In the processing of building the streamsx.healthcare project, which employs the microservice architecture, we start to see common patterns and challenges in creating microservices for Streams.  

The goal of the repository is:
- Provide example and best practises documentation in writing microservices for Streams
- Create utilities or tools that will help the building of microservices
- Create infrastructure and utilities to help clients define and launch applications using microservices
- Provide a repository to collaborate with the broader Streams community in defining microservices.

Initial contribution will be some example microservices that demonstrate some of the best practises.

**Comment by ddebrunner** [comment]
Can you expand on the example microservices that would be in the repo? 

Just wondering what they would look like or is it sufficient to point to existing ones in health/transportation.

**Comment by chanskw** [comment]
This is the first one.. I am still working on it so it may not be 100% "correct".... 

https://github.com/IBMStreams/streamsx.health/tree/develop/samples/ExampleService/com.ibm.streamsx.health.example.service

While it is easy to define a single microservice, it becomes more challenging when you try to create multiple services that make up the application.  Challenges include:
1)  pub/sub topic guildelines (you mentioned MQTT Style, which I am going to implement in the health platform
2)  versioning
3)  how to customize a service?
4)  how to build ?
5)  how to launch?

The goal of the repository is to answer some of these questions and make it easier.  I would like it to be a top level project so that it is a more visible project for collaboration, and also allowing us to have some standard in place. Putting it under streamsx.health or streamsx.transportation does not seem to have enough visibility and allow for such cross-collaboration.

**Comment by ddebrunner** [comment]
I think the concept is good, I'm just trying to understand what the examples would look like.

Seems if they are related to health then they should be in the health toolkit and maybe this repo just references them.

Or maybe examples in this repo would be totally generic and not related to a specific field, eg. the sample in topology just publishes a simple stream and has a another service to consume it.

**Comment by chanskw** [comment]
Yes that is the goal.  The samples will be generic.

**Comment by ddebrunner** [comment]
+1

Note that the `streamsx` package already has a (poorly documented) mechanism for linking a job config with an application/microservice.

**Comment by mikespicer** [comment]
+1

**Comment by chanskw** [comment]
Created repo.  Added @ddebrunner and @cancilla as initial committeres
