### ISSUE TITLE
Proposal: Create a repo for Python package wrapping SPL standard toolkit.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/administration#128]
To allow easy use of SPL Standard toolkit operators from Python applications I've been working on  creating a `streamsx.standard` package that provides high-level functions that invoke the SPL operators under the covers, e.g:

```
# Create a structured stream from a CSV file.
s = files.csv_reader(topo, 'tuple<uint64 seq, rstring a, float64 b>', file='/tmp/data.csv')
```

```
# Throttle a stream
s = utility.throttle(s, rate=1000)
```
```
# Deduplicate a stream
s = utility.deduplicate(s, period=10.0)
```
The initial version of the repo is here:
https://github.com/ddebrunner/pypi.streamsx.standard

and has a number of initial functions and some tests of those functions, as well as the ability to create documentation.

Python packages for other toolkits that are open source on github would create a package within their existing repo, rather than create new repos, e.g. see https://github.com/IBMStreams/streamsx.messagehub/issues/18

Initially the package would be at a version < 1.0, e.g. 0.1 as the apis are still subject to change and more functionality should probably be added before 1.0 is released.

RepoName: `IBMStreams/pypi.streamsx.standard`

**Comment by mikespicer** [comment]
+1

**Comment by chanskw** [comment]
+1

**Comment by chanskw** [comment]
Done
