### ISSUE TITLE
New toolkit repository proposal: streamsx.protobuf

### ISSUE THREAD

**Issue by bmwilli** [IBMStreams/administration#130]
I would like request a new toolkit repository called streamsx.protobuf

The purpose of this toolkit is to provide operators that can read in protobuf messages into tuples, and to write tuples as protobuf messages.

There is a utility:
spl-schema-from-protobuf that will read the protocol format file (.proto) and produce SPL Types

There are two primary operators:
ProtobufParse: given the .proto file, this operator takes in a blob and produces tuples that have a schema generated by the spl-schema-from-protobuf utility
ProtobufBuild: given the .proto file, this operator takes in a tuple matching the schema produced by the spl-schema-from-protobuf utility and produces a blob containing the protocol buffer

There are two utility operators:
ProtobufFileSource: read in a file of pseudo-standard protocol buffers ([4-byte lenth][protocolbuffer][4-byte length][protocolbuffer]...) and passes each protocol buffer out as a blob attribute on a tuple.
ProtobufTCPSource: accepts tcp connection and data in the same format as ProtobufFileSource above

If there are any questions, please let me know.

Brian Williams

**Comment by ddebrunner** [comment]
+1 with caveat of need to see why specific source operators are needed. The goal has been to separate out parsing from sources.

**Comment by bmwilli** [comment]
They are not required, which is why I called them "utility" operators. Our customer needed them because the system they received data from followed the suggestion here: [https://developers.google.com/protocol-buffers/docs/techniques#streaming]

If there is an existing operator(s) that would provide this format input, then we could remove them and give a sample with the new approach.

**Comment by ddebrunner** [comment]
Yeah - the need for them or not can be resolved once the project is created.

**Comment by mikespicer** [comment]
+1

**Comment by leongor** [comment]
+1

вт, 6 февр. 2018 г. в 1:54, Mike Spicer <notifications@github.com>:

**Comment by BruceGlassford** [comment]
Reason for combining the operators - if you use TCPSource, in binary mode, you won't get a block until it's full since it doesn't know the data is ready.  There's no parsed format that exists for the <nByteLength><rawdata> structure.  If the data coming in is not continuous, splitting the parsing and sources may insert significant latency.   Using a very small block size solves this, but increases network overhead drastically, impacting throughput.

**Comment by bmwilli** [comment]
How many +1 votes does it take to get it approved and created?

Thanks,
Brian

**Comment by petenicholls** [comment]
There is no fixed number required....the hold up typically is whether I notice the voting has occurred.  Will create repos tomorrow morning.

**Comment by petenicholls** [comment]
repos streamsx.protobuf set up with default license and readme, Brian William added as initial committer.  Closing.
