### ISSUE TITLE
Function proposal: parseDateTime

### ISSUE THREAD

**Issue by leongor** [IBMStreams/administration#133]
Recently we've developed `parseDateTime` function for Streams Designer. Here 2 main reasons behind it:
1. `fromIso8601ToTimestamp` function from `com.ibm.streamsx.datetime` toolkit is very strict, while customers frequently use timestamps without time zones or nanseconds.
2. A single tuple can easily have multiple timestamps to parse, so performance is crucial. `parseDateTime` is built over [Boost.Spirit](https://theboostcpplibraries.com/boost.spirit), one of the blazing fast C++ parsers.

**Comment by brandtol** [comment]
I would propose to merge this functionality to com.ibm.streamsx.datetime to reduce the number of toolkits that handle similar tasks. In the long term I think this function as well as the functions from streamsx.datetime should go into the standard SPL toolkit in spl.time namespace.

**Comment by ddebrunner** [comment]
Shouldn't this be an issue in `streamsx.datetime`?

**Comment by leongor** [comment]
@ddebrunner Yes, right. I'll move it there.

**Comment by leongor** [comment]
Moved to [streamsx.datetime](https://github.com/IBMStreams/streamsx.datetime/issues/13)
