### ISSUE TITLE
Proposal: streamsx.nats

### ISSUE THREAD

**Issue by resinten** [IBMStreams/administration#134]
I would like request a new toolkit repository called streamsx.nats

The purpose of this toolkit is to provide source and sink operators for [NATS](https://nats.io/)

There are / will be two primary operators:
* NatsSource: read data from a NATS topic / queue group / set of topics and emit the messages' data to a blob attribute.
* NatsSink: write data to a NATS topic based on an incoming blob attribute. Potentially support variable topic name based on tuple attribute.

If there are any questions, please let me know.

Brian West

**Comment by ddebrunner** [comment]
+1 with usual request to name operators for the function they perform, not just use 'Source' and 'Sink'.   

Typically use the terms of the system being integrated with, maybe `NatsPublish` instead of `NatsSink` (from a quick look at the docs, there may be better terms).

**Comment by mikespicer** [comment]
+1

**Comment by resinten** [comment]
@ddebrunner That's fair. I'm thinking that NatsPublish and NatsSubscribe should be good names for the Sink/Source.

**Comment by resinten** [comment]
How many +1s does it take to get to the center of a repo request? :-)

**Comment by ddebrunner** [comment]
@schulz2 @natashadsilva Can the repo be created?

**Comment by petenicholls** [comment]
Created streamsx.nats, Brian has admin permissions.  Let me know if there are problems.
