### ISSUE TITLE
Propsal to create a new streamsx.inetserver reopsitory

### ISSUE THREAD

**Issue by joergboe** [IBMStreams/administration#137]
Separate the jetty-sever based operators (rest) and the websocket-server operators of the streamsx.inet toolkit from the client operators and functions. 

The **client operators** and **functions** shall continued in the existing **toolkit streamsx.inet**.
The **server based operators** shall go into a new toolkit **streamsx.inetserver**.
The toolkits inet and inetserver shall have exclusive name spaces:

Toolkit streamsx.inet:
com.ibm.streamsx.inet
com.ibm.streamsx.inet.http
com.ibm.streamsx.inet.ftp

Toolkit streamsx.inetserver:
com.ibm.streamsx.inet.rest
com.ibm.streamsx.inet.wsserver
The namespaces of the server based operators are not changed to minimize the impact for the users of the current inet toolkit. The users are not required to make code changes, when moving from the former inet toolkit to the new inet- and inetserver-toolkit. The only required change is a adaptation of the toolkit path for the spl-compiler.

The inet-toolkit shall change the major version from 2.9.6 to 3.0.0
The inetserver-toolkit shall start with version 3.0.0 to document the descent from inet-toolkit.

The reasons for that split are discussed were throroughly discussed a year ago:
https://ibm-cloudplatform.slack.com/archives/C3XD5NE8H/p1491405012277552?thread_ts=1491207411.956117&cid=C3XD5NE8H

Now the customers ask for clarification.

**Comment by schubon** [comment]
Created repository: https://github.com/IBMStreams/streamsx.inetserver
