### ISSUE TITLE
Discussion about the need of new repos for toolkit pypackages

### ISSUE THREAD

**Issue by markheger** [IBMStreams/administration#139]
Currently the python wrapper packages are part of a `pypackage` branch in the toolkit repo, e.g. `streams.messagehub`, `streamsx.objectstorage`, `streamsx.inet` etc.

Shall we create new repos for the python wrapper packages, like `pypi.streamsx`?
Advantage: The new repo could contain releases (tags) for package versions, independent from the toolkit version.
SPL toolkits do not depend on python packages. Python packages can use toolkits installed in cloud (build service).

Proposed new repos:
* pypi.streamsx.database
* pypi.streamsx.objectstorage
* pypi.streamsx.kafka
* pypi.streamsx.elasticsearch
* pypi.streamsx.inet
* pypi.streamsx.messagehub

**Comment by ghost** [comment]
Yes, this would be a good idea because we could use distinct tags for toolkit releases and Python package releases. Now we see also the toolkit releases in Pypi because the toolkit repos are connected with Pypi.

**Comment by ddebrunner** [comment]
Yeah, a separate repo is probably better, makes branching easier.

At some point we might have the Python package include a hidden release SPL toolkit, so if the build service does not have the latest one it be supplied, but that would still seem to work with separate repos.

**Comment by joergboe** [comment]
Yes, the pypi code shall use a separate repository. Between Streams Toolkit repository and python wrapper code, there is no code in common, no description can be used for both. The only link is the  mapping of the python mapper release to the required Streams toolkit release.
- The required toolkit release must be documented in python wrapper code
 and
- The required toolkit release shall be checked at runtime
 or 
- The required toolit shall be bundled into the pypi package

**Comment by markheger** [comment]
@schubon 

Please create the following repos:

* pypi.streamsx.avro
* pypi.streamsx.database
* pypi.streamsx.elasticsearch
* pypi.streamsx.eventstreams
* pypi.streamsx.hdfs
* pypi.streamsx.inet
* pypi.streamsx.kafka
* pypi.streamsx.objectstorage

Top level description similar to streamsx.pypi package.
Contributors for all repos: anouri, joergboe, RolefH, markheger

**Comment by schubon** [comment]
Basic setup done. If you need more or discover a problem, just ping me.
