### ISSUE TITLE
Repository request : WikiRecent

### ISSUE THREAD

**Issue by siegenth** [IBMStreams/administration#141]
Wikipedia provides a realtime feed of recent updates to it's content. This repository contains examples and tutorials of live processing using this feed.

Example of utilizing data derived solely from the feed, a dashboard snapshot showing top editors, articles and  languages of updates in the last 30 seconds
<img width="400" alt="image" src="https://user-images.githubusercontent.com/3303300/56430998-328c4b80-627d-11e9-942b-a5ef34ce8d42.png">

Example of live image analysis, dashboard snapshot of image submitted to Wikipedia and the results of the 'Facial Emotion Classifier' graphed.
<img width="168" alt="image" src="https://user-images.githubusercontent.com/3303300/56431849-23f36380-6280-11e9-87ad-4ddc2b6b2cea.png">

**Comment by ddebrunner** [comment]
Added https://github.com/IBMStreams/sample.wikirecent and added @siegenth as admin.

[Trial of policy where repos for samples are created on-demand]
