### ISSUE TITLE
Repository proposal: sample.notebook_templates

### ISSUE THREAD

**Issue by natashadsilva** [IBMStreams/administration#142]
Proposal to have a repository to host the sample notebooks included in ICP4D.
This would allow us to update them between releases and also make them available to other Python developers, e.g. for Watson Studio or on-prem. 
The repository will specifically be for these notebooks:

- Streams-BasicSample.ipynb	
- Streams-DatabaseSample.ipynb
- Streams-EventStoreSample.ipynb	
- Streams-EventStreamsSample.ipynb	
- Streams-PMMLScoringSample.ipynb	
- Streams-RollingAverageSample.ipynb

**Comment by ddebrunner** [comment]
I think the plan is to have sample repos start with 'sample', e.g. https://github.com/IBMStreams/sample.wikirecent.

Note sure `sample.notebook_templates` would be a good name, but struggling for a better one.

**Comment by natashadsilva** [comment]
Or sample.general_notebooks?

**Comment by natashadsilva** [comment]
@ddebrunner  If you are ok with it, could you create the repo please? I don't have permissions to do so.

**Comment by ddebrunner** [comment]
`sample.starter_notebooks` ?

**Comment by natashadsilva** [comment]
That is ok by me.

**Comment by ddebrunner** [comment]
Created https://github.com/IBMStreams/sample.starter_notebooks
