### ISSUE TITLE
New repo samples.forecast_with_r for Streams flows/R demo

### ISSUE THREAD

**Issue by natashadsilva** [IBMStreams/administration#143]
The sample code for this [demo](https://www.youtube.com/watch?v=gZAoDOus0vc&feature=youtu.be) has a few pieces, and having it in its own repo makes it easy for others to try.
I'm also open to suggestions for repo name :)

**Comment by markheger** [comment]
I suggest `sample.forecast_with_r`

**Comment by markheger** [comment]
repository created
