### ISSUE TITLE
Rename streamsx.cppws

### ISSUE THREAD

**Issue by markheger** [IBMStreams/administration#144]
There is no need that the repository name contains the implementation (cpp/C++)

## Proposal

Rename `streamsx.cppws` to `streasmx.websocket`

**Comment by schubon** [comment]
I agree with Mark's remarks.

**Comment by markheger** [comment]
@nysenthil @joergboe what do you think about renaming the repo and the toolkit?

**Comment by nysenthil** [comment]
Dear friend Mark-Oliver,
“What's in a name? that which we call a rose. By any other name would smell as sweet.”

― William Shakespeare, Romeo and Juliet 

I have some naming ideas. But, I will have to check with the two large banks and a utility company who are already using this toolkit in their business critical scenarios to see what they think and how it will impact their work.

**Comment by joergboe** [comment]
How many customer installations are affected, when we rename?
If we rename the toolkit we should rename the namespace as well.
   com.ibm.streamsx.websocket

**Comment by nysenthil** [comment]
Hi Joerg,
I already mentioned above that two large  banking customers and a large energy utility company. The utility company is in the process of doing their system testing now. This week, they have asked  for couple of more changes which I'm in the process of doing. We have  to wait until the first week of  July/2020 before we can do a wholesale toolkit name change and namespace  change.

I have been thinking about a new name. In honor of the popular IBM Mainframe zOS tool, I'm inspired to suggest that name as shown below.

streamsx.cppws     to     streamsx.wscon
com.ibm.streamsx.cppws      to       com.ibm.streamsx.wscon

In the Mainframe world, wscon stands for workstation connectivity. In our context here, it is WebSocket connectivity. It is just a thought. As  expressed  in my  literary quote above, I'm interested in the contents and quality of the toolkit more than the name of the toolkit.

-- Senthil.

**Comment by joergboe** [comment]
I vote for name: streamsx.wscon and ns: com.ibm.streamsx.wscon

**Comment by markheger** [comment]
> I vote for name: streamsx.wscon and ns: com.ibm.streamsx.wscon

+1

**Comment by natashadsilva** [comment]
Hi, can we include websocket in the name? It is easier for people to know what it's for, and also to find it, for example when searching on the Streams Github project page for a repository. 
I think for that reason I would prefer Mark's original suggestion of streamsx.websocket.

**Comment by petenicholls** [comment]
Prefer streamsx.websocket.  SImple, clear what the toolkit does, likely search term.

The other contender requires inside knowledge of IBM terms and is harder to associate with websockets.

**Comment by nysenthil** [comment]
Dear colleagues,
All of you are the winners in finding a fantastic new name for this toolkit. I'm currently making  changes for a feature request from an important customer which should be completed by the July 4th long weekend. During the week of July/06/2020, we will do the wholesale name change of this repository to streamsx.websocket and the  toolkit namespace to com.ibm.streamsx.websocket. I just now sent an alert about this upcoming change to the three important U.S based customers who are implementing their major use cases around this toolkit.

**Comment by joergboe** [comment]
All done. We can close this issue.
