### ISSUE TITLE
images for IBMStreams repository guidelines

### ISSUE THREAD

**Issue by ejpring** [IBMStreams/administration#16]
copy repository URL button, from github.com

![image](https://cloud.githubusercontent.com/assets/4257805/2550190/7f6fc692-b680-11e3-9239-24f2d6db7213.png)

clone repository button, from EGit

![image](https://cloud.githubusercontent.com/assets/4257805/2550201/90e656b6-b680-11e3-90b6-51a6a0ed283b.png)

new empty repository, from EGIT

![image](https://cloud.githubusercontent.com/assets/4257805/2550214/a56f5ac4-b680-11e3-9168-ac45b6060b6a.png)

new toolkit operator, from Eclipse

![image](https://cloud.githubusercontent.com/assets/4257805/2550778/f7cbda8a-b686-11e3-8a25-cf750cc12f81.png)

add toolkit to repository, step A, from Eclipse

![image](https://cloud.githubusercontent.com/assets/4257805/2552868/d3a0a10a-b69e-11e3-9281-2d9ac5b5e1fa.png)

add toolkit to repository, step B, from Eclipse

![image](https://cloud.githubusercontent.com/assets/4257805/2551416/77998198-b68e-11e3-909d-473e7bffb703.png)

git directory and file icon annotations, from Eclipse

![image](https://cloud.githubusercontent.com/assets/4257805/2553279/8fa44876-b6a3-11e3-85e5-a1c3f58fdcea.png)

team commit button, from Eclipse

![image](https://cloud.githubusercontent.com/assets/4257805/2555521/a31fd312-b6c0-11e3-9267-98ddd242bbb4.png)

team push to upstream button, from Eclipse

![image](https://cloud.githubusercontent.com/assets/4257805/2556166/8b99e6f4-b6cc-11e3-853b-02ec1885a33c.png)

team pull button, from Eclipse

![image](https://cloud.githubusercontent.com/assets/4257805/2556183/2e0de53e-b6cd-11e3-8139-fdd7850d4371.png)

changed files, from Eclipse

![image](https://cloud.githubusercontent.com/assets/4257805/2556246/ec38ecce-b6ce-11e3-87a4-5fafe48334f3.png)

adding a sample to a repository, from Eclipse

![image](https://cloud.githubusercontent.com/assets/4257805/2556854/196fe210-b6e3-11e3-94a4-ac94940c135a.png)

toolkit and sample in git, from EGit

![image](https://cloud.githubusercontent.com/assets/4257805/2556863/1ccfb006-b6e4-11e3-986a-b0ffd4deb6c9.png)

displaying version numbers:

![image](https://cloud.githubusercontent.com/assets/4257805/2556920/a0293966-b6e6-11e3-857a-bc37537ea5c6.png)

setting version number:

![image](https://cloud.githubusercontent.com/assets/4257805/2556917/83242af6-b6e6-11e3-85d4-4bf33db51ea2.png)

add SSH protocol to Clone Git Repository dialog:

![image](https://cloud.githubusercontent.com/assets/4257805/2570147/7826fd0c-b8f5-11e3-92c9-b45619a17324.png)

select Import for Clone Git Repository dialog:

![image](https://cloud.githubusercontent.com/assets/4257805/2570186/0196fcea-b8f6-11e3-89e2-3f79d4e195f6.png)

**Comment by chanskw** [comment]
Closing.. unsure what to do with this. Please reopen if this is still needed.

**Comment by hildrum** [comment]
Nothing needed to be done here, it's just what you can't easily put images in wiki pages, while you can easily put images in issues and then link the wiki page to the images in the issue.

**Comment by chanskw** [comment]
Closing then. Thanks Kris.
