### ISSUE TITLE
Sound

### ISSUE THREAD

**Issue by jchailloux** [IBMStreams/administration#18]
Link to a toolkit that use libsnd.
https://www.ibm.com/developerworks/community/forums/html/topic?id=8753a6fe-8d0a-471c-9ea7-502af3dfdc0d&ps=25

This toolkit permits to read sound files

**Comment by chanskw** [comment]
There has been no action about this since May 2014.
I am closing this issue.  If you still would like to contribute a sound repository, please reopen and we can work on it.

Thanks!
