### ISSUE TITLE
Display

### ISSUE THREAD

**Issue by jchailloux** [IBMStreams/administration#19]
Link to a toolkit that use GNU Plot to display near real-time data

https://www.ibm.com/developerworks/community/forums/html/topic?id=6c3d3084-38f3-4177-a45e-1cbce7a017f5&ps=25

**Comment by chanskw** [comment]
Going through some of the work items here.  Do you think this should be combined into the streamsx.visualization project?

**Comment by chanskw** [comment]
Closing this one due to lack of activity. Please reopen if you still want to contribute.
