### ISSUE TITLE
Working with toolkit/repository collaborators 

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/administration#29]
Is there a way in github we can work with repository collaborators who only have read access to the repository, so that for example issues can be assigned to them?

It's good to have volunteers working on the code who are not yet committers, but how to manage that if  they can't have issues assigned to them, or can't assign issues to themselves.I think at ASF anyone with a user identifier can assign themselves a JIRA issue, regardless of their commit status.

**Comment by chanskw** [comment]
I did not find any way to do this....

**Comment by chanskw** [comment]
I found that perhaps we can add the person as an "outside collaborator".  I haven't tried it, but if there is someone you would like to suggest as an outside collaborator, we can try and see if it works.

**Comment by mikespicer** [comment]
If they haven't already contributed the fix could we try this with Riccardo and Claudio's enhancements to the HBase toolkit?

**Comment by chanskw** [comment]
Great suggestion!  I set up a "collaborator" team for HBase.  This team has read-only access.  I am waiting for them to accept the invitation and see what happens.

**Comment by chanskw** [comment]
I used outside collaborator in the HBase toolkit... I was able to assigned the issue to Riccardo.  Seems to work well. 

In the future, if you have someone who you want to collaborate with, please open an issue here, and we can add them as an outside collaborator.
