### ISSUE TITLE
What is the process for contributing samples?

### ISSUE THREAD

**Issue by scotts** [IBMStreams/administration#36]
I have created two issues under "samples" for pulling in my two sample repositories (found at https://github.com/scotts/LogWatch and https://github.com/scotts/LogWatchUDP). However, I now suspect that no one monitors the "samples" repository.

So, several questions:

1. Should I contribute samples by opening an issue under "toolkits"?
2. If "yes" to 1, then what is the purpose of the "samples" repository?
3. If "yes" to 1, then is "toolkits" the best name for this repository? Perhaps we should name it "administration" if it is for managing all issues related to tookits, utilities, samples and tutorials.

**Comment by chanskw** [comment]
Closing... I think this is resolved.
