### ISSUE TITLE
Adding external libraries as dependencies

### ISSUE THREAD

**Issue by rohitsw** [IBMStreams/administration#37]
I would like to discuss the best way to add external libraries (with acceptable licenses) required by our toolkits to the build process.
For the Yarn resourcemanager, we used maven to specify our dependencies and build.
Should we consider maven for toolkits as well?
An alternative would be to do this manually. For every library/dependency, use an environment variable to point to it and include it in the operator and build.xml.
Any other alternatives/thoughts?

**Comment by chanskw** [comment]
I believe this res resolved.  The general guideline for toolkit development is to use Maven to pull in dependencies.

Maven targets are created in toolkits to only pull the dependencies, avoiding build conflicts with Studio.  Instructions are created in toolkit to show people how to download the dependencies.

For the end-user, toolkit releases are made, where external dependencies are part of the package.
