### ISSUE TITLE
streamsx.ps

### ISSUE THREAD

**Issue by nysenthil** [IBMStreams/administration#53]
streamsx.ps is a Streams Process Store toolkit which will allow sharing of application specific state among multiple operators that are fused together into a single PE (Processing Element).

**Comment by hildrum** [comment]
+1

**Comment by chanskw** [comment]
+1

**Comment by rohitsw** [comment]
Instead of having two toolkits for streamsx.ps and streamsx.dps, could the operators etc be in a single toolkit?

**Comment by nysenthil** [comment]
Hi Rohit,
The Process Store (ps) and the Distributed Process Store (dps) serve completely two different needs with respect to data sharing. They have nothing in common other than their similar sounding names. Implementations for both of them are entirely different. It is better to keep them as separate toolkits so that they can evolve independent of each other.

Thank you for your vote,
Senthil.

**Comment by leongor** [comment]
+1

**Comment by petenicholls** [comment]
created streamsx.ps
