### ISSUE TITLE
streamsx.dps

### ISSUE THREAD

**Issue by nysenthil** [IBMStreams/administration#54]
streamsx.dps is a Streams Distributed Process Store (DPS) toolkit. It allows the Streams operators belonging to one or more applications running on one or more machines to share application specific state in a seamless way using an external NoSQL K/V data stores. Some of the popular K/V data stores supported by this toolkit are listed below:

1) memcached
2) Redis
3) Cassandra
4) IBM Cloudant
5) HBase
6) Mongo
7) Couchbase

**Comment by hildrum** [comment]
+1

**Comment by chanskw** [comment]
+1

**Comment by leongor** [comment]
+1

**Comment by petenicholls** [comment]
created streamsx.dps
