### ISSUE TITLE
streamsx.tcp

### ISSUE THREAD

**Issue by nysenthil** [IBMStreams/administration#55]
MultiConnectionTCPServer is a toolkit that currently exists in the IBM developerWorks Streams Exchange. This is one of the many things our fantastic Streams colleague Bugra designed and created when he was working at the IBM T.J.Watson Research Center. 

In a short sentence, this toolkit is simply a gem.  This toolkit alone impressed at least half a dozen customers and accelerated their decision making to buy Streams licenses.

To meet the new requirements from those customers, a few of us (Vitali, Senthil and Frank) have enhanced this toolkit over the past 3 years. I would like to give a new start by moving this toolkit code from Streams Exchange to IBMStreams GitHub with all the new enhancements. Please approve this new toolkit to be housed here since it is one of the sought after Streams assets by our paying customers.

Thank You,
Senthil.

**Comment by hildrum** [comment]
+1

**Comment by leongor** [comment]
+1

**Comment by petenicholls** [comment]
created streamsx.tcp.
