### ISSUE TITLE
Request for new repository: streamsx.network.utils

### ISSUE THREAD

**Issue by cancilla** [IBMStreams/administration#58]
I have created a toolkit called **com.ibm.streamsx.network.utils**. It is comprised of SPL functions that work specifically with IPv4 IP addresses. These are mainly utility functions that allow users to quickly perform operations on IP addresses. I believe this toolkit will be useful to customers who are doing any sort of work with network log files, cyber security, DNS records, etc. 

Some of the functions included in the toolkit are:

boolean **isInNetwork**(rstring networkCIDR, rstring ip) - returns true if the IP address is in the given network
list<rstring> **getAllAddressesInNetwork**(rstring networkCIDR) - returns a list containing all IPs in a given network
boolean **isPrivate**(rstring ip) - returns true if the IP address is reserved for private networks (192.x.x.x, etc)
boolean **isGlobal**(rstring ip) - returns true if the IP address is a globally resolvable address

**Comment by chanskw** [comment]
+1, I propose to simply calling the repository / toolkit as com.ibm.streamsx.network.  The project be used to provide functions related to analyzing network data.

**Comment by cancilla** [comment]
Regarding calling the toolkit com.ibm.streamsx.network, I do not want to confuse this project with other network-related projects that may be in the works.

**Comment by chanskw** [comment]
There isn't a network project on Github yet.  If we get other contributions related to analyzing network traffic in the future.  We may also want to contribute those to the streamsx.network project.  Having multiple network projects may become too confusing in the long run.

**Comment by cancilla** [comment]
Agreed. I will rename the toolkit to com.ibm.streamsx.network

**Comment by ddebrunner** [comment]
There was an early comment about adding the network packet analyzer toolkit that is on the old streams exchange,  would this toolkit be merged with that one if it was contributed?

**Comment by ddebrunner** [comment]
+1 to the toolkit, I also have some operators , functions and types for IPV4 addresses and packets

**Comment by chanskw** [comment]
Dan, I will take a look at that and try to merge the toolkit from streamsexchange here as well.  Goal is to have a single toolkit for all network data related functions.

**Comment by leongor** [comment]
Still I'd leave namespace to be com.ibm.streamsx.network.utils

**Comment by chanskw** [comment]
@leongor Yes... agreed.  I am just proposing that we rename the toolkit name.. we will use namespace to help separate functions.

**Comment by ddebrunner** [comment]
Might make sense to have the name space represent what the functions are related to , in this case ip, e.g com.ibm.streamsx.network.ip

**Comment by cancilla** [comment]
The functions I have currently exist in the com.ibm.streamsx.network.utils.ipv4 namespace. I think it will be important to distinguish between utilities that act on IPv4 vs. IPv6 addresses

**Comment by mikespicer** [comment]
+1 for the toolkit. I'm neutral on naming.

**Comment by hildrum** [comment]
+1 for the toolkit.   I think "network" has the potential to be confused with inet toolkit (or other toolkits using network protocols) so something to make it clear this is for analyzing network-related traffic would be good, eg "network.analysis".

**Comment by leongor** [comment]
+1, agree on ip4 addition to the namespace.

-----Original Message-----

**Comment by chanskw** [comment]
So, based on the feedback, here's the proposal on what we will do.

repository name:  streamsx.networkAnalysis
toolkit name:  com.ibm.streamsx.networkanalysis
namespace for the initial function set:  com.ibm.streamx.networkanalysis.util.ipv4

Once the repository is created, we will look at streams exchange to see if the network packet analyzer can be merged into here.  

I will leave this open for one more day before I create the repository.  Please let me know if there is any objection to this proposal.

**Comment by ddebrunner** [comment]
+1

Minor comment that I would drop 'utils' from com.ibm.streamsx.network.utils.ipv4, and just have com.ibm.streamsx.network.ipv4, so that it's just ipv4 related stuff, not sure of the value of adding 'utils'.

**Comment by chanskw** [comment]
Created streamsx.networkAnalysis repository.
James Cancilla is the initial committer to the project.
