### ISSUE TITLE
"Creating a web page..." document is missing info

### ISSUE THREAD

**Issue by cancilla** [IBMStreams/administration#61]
The "Creating a web page for your toolkit" document (https://github.com/IBMStreams/administration/wiki/Creating-a-web-page-for-your-toolkit-%28draft%29) is missing some key pieces of information. Specifically, the fact that you need to have build.xml files in both the repository root directory and the toolkit root directory. Furthermore, there are specific ant targets that need to be included in each of these files in order for the updateWeb.pl script to work. 

There needs to be a more generic set of files (i.e. without inet-specific stuff) that can easily be dropped into a new repository and run.

**Comment by leongor** [comment]
Agree.
+1

**Comment by hildrum** [comment]
Added the info saying you need a build file.  Please feel free to edit more to make the page more useful.

**Comment by chanskw** [comment]
Closing.  Please reopen if more info is needed.
