### ISSUE TITLE
Proposal: streamsx.sparkanalytics project

### ISSUE THREAD

**Issue by ankitpas** [IBMStreams/administration#63]
I am proposing that we create a project for supporting spark analytics in Streams.

The goal of the project is to allow users to incorporate Spark's machine learning models within their Streams application.

If there are other ideas, please let me know.

**Comment by chanskw** [comment]
+1

Should we name this as streamsx.spark to make the project more open for future integration with Spark, in addition to the analytic capabilities?

**Comment by mikespicer** [comment]
+1 for a toolkit.  In terms of naming we could either have a more generic toolkit called streamsx.spark which could contain all future spark related operators or have a more specific one streams.sparkMLLib which focusses on the Spark MLLib functionality

**Comment by ddebrunner** [comment]
+1

**Comment by hildrum** [comment]
I prefer streamsx.sparkMLLib, or streamsx.sparkml or something else that gives people an idea of what's included.

**Comment by leongor** [comment]
+1

**Comment by Yifat-Yulevich** [comment]
+1 Two specific toolkits will be less confusing, using the Spark MLLib will be for Streams real-time scoring while the other will be used when both Streams and Spark running together.

**Comment by chanskw** [comment]
Closing the vote.. will create repository today.
Will name repository as streamsx.sparkMLLib

**Comment by chanskw** [comment]
Ankit - I created repository here:
https://github.com/IBMStreams/streamsx.sparkMLLib

I added you as committer and also generated io pages for web site.
