### ISSUE TITLE
Proposal:  IBMStreams.github.io project

### ISSUE THREAD

**Issue by chanskw** [IBMStreams/administration#64]
Proposal is to create a top-level Github IO pages repository for the IBM Streams organization.
Repository will host a website for the IBM Streams organization on Github.

Initial committers:  Pete Nicholls (@petenicholls), Samantha Chan (@chanskw), Alex Cook.

**Comment by hildrum** [comment]
+1
What's the plan for what content goes on this page vs. on StreamsDev?  Will this Github IO page be mostly linking to the github projects?

**Comment by mikespicer** [comment]
+1
My view is that the github io site should have information and links on the github projects but also have articles which we want to maintain and evolve as we release new versions of streams. Streamsdev would continue to have blog posts, the forum and unversioned articles.

**Comment by ddebrunner** [comment]
+1

Would be good to have top-level pages that allow users to find released versions of the toolkits easily.I think currently too hard for an SPL developer who just wants to use a toolkit to find one.

**Comment by leongor** [comment]
+1
Agree.

**Comment by chanskw** [comment]
closing... created repository
