### ISSUE TITLE
Create a mechanism to have a multiple-toolkit release.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/administration#66]
I tried to add something to the streamsx.transportation toolkit and there are a number of steps involved which make it less than easy.

First issue is that several toolkits have not produced a release, thus I have to clone the repo and build each toolkit. This can be fixed by encouraging projects to produce releases that can be used directly by SPL developers.

Even, if the toolkits have releases, I then have to download three toolkit releases, untar them etc. It would be useful to have a meta-release, that contains the latest releases of multiple toolkits, maybe two variants:

toolkits only
toolkits + samples

And then there could be variants for specific Streams releases, 4.0, 4.0.1 etc, as needed.

**Comment by hildrum** [comment]
+1

I originally didn't see what you were getting at with this proposal, but now I see that for someone who just wants to use toolkits, it would be very convenient to just be able to download a single package.  Of the ways of distributing this (via the web page, off the wiki, off the release page), using the release page of the administration repository seems to make the most sense.  

An alternate possibility is that something like the streamsx.transportation toolkit could create a "super release", which contains not only streamsx.transportation, but all the toolkit the streamsx.transportation toolkit needs.

**Comment by leongor** [comment]
+1

Toolkit installation should be as simple as possible.
If there are 2 alternatives:
1. The toolkit seems to be very small, but requires from user to run scripts, download and install additional dependencies, run yum, define environment variables.
2. The toolkit is fully packaged, but requires from user zero effort to run it.

I'm pretty sure that an average user will choose the second option.

**Comment by ddebrunner** [comment]
Should this be a new repo that just contains scripts that create the meta-bundle.

streamsx.toolkits

??

**Comment by hildrum** [comment]
I think it would be better to use the admin repository rather than creating a new one.  This is a question of how to manage what we have, so I think it does fit under the administration umbrella.   If we bundle anything up to be download-and-go, we could put that as a release in the administration repository, and any scripts used to make it easier for people to get toolkits could go in the repository itself.
