### ISSUE TITLE
Proposal:  streamsx.healthcare

### ISSUE THREAD

**Issue by chanskw** [IBMStreams/administration#70]
Proposal to create a streamsx.healthcare project on Github.

The project will focus on realtime analytics and monitoring of patient's data from medical devices.

We are soliciting ideas for project contribution.

**Comment by petenicholls** [comment]
+1 for this project.

**Comment by rrea** [comment]
+1 for this - been looking forward to seeing this

**Comment by mikespicer** [comment]
Can you elaborate on the proposed initial content and intended future direction please.

**Comment by ddebrunner** [comment]
I think this would be good but only if there was some initial contribution, having an empty repository lying around waiting for ideas does not give the impression of an active community.

I believe there are some open source healthcare algorithms around but I couldn't find them in a quick search.

**Comment by hildrum** [comment]
Should this issue be closed since `streamsx.health` has already been created?

**Comment by chanskw** [comment]
Repository created, closing. 
Will provide more information about this repository in the project itself.
