### ISSUE TITLE
Remove streamsx.logging

### ISSUE THREAD

**Issue by chanskw** [IBMStreams/administration#74]
This repository has been opened since May 2014 and have had no contribution.
Propose to remove.

**Comment by hildrum** [comment]
+1

**Comment by leongor** [comment]
+1

**Comment by ddebrunner** [comment]
+1

**Comment by mikespicer** [comment]
+1
The idea is still good but I checked with @siegenth and he doesn't expect to have time to work on it in the near future.

**Comment by markheger** [comment]
deleted
