### ISSUE TITLE
Proposal:  streamsx.documentation project

### ISSUE THREAD

**Issue by chanskw** [IBMStreams/administration#75]
Proposing a streamsx.documentation project for sourcing documentation for Streams development guides.  This allows us to write general documentation in Github markdown languages.  Customers and community can easily provide feedback and contribution to our documentation from this project.

This project will only contain gh-pages branch.  And we will use Github IO Pages to serve documentation. The documentation can be written in HTML or Github markdown language.  We can link to this documentation from StreamsDev as well as the IBM Streams Github.io site.

Initial contribution: 
* Streams 4.1 Getting Started Guide for QSE VM
* Java Operator Development Guide - we will create a quick outline and then slowly work on this guide in the open.

**Comment by Alex-Cook4** [comment]
+1

**Comment by mikespicer** [comment]
+1

**Comment by leongor** [comment]
+1

**Comment by petenicholls** [comment]
+1

**Comment by chanskw** [comment]
Thanks.. created streamsx.documentation repository.
Initial Committers:  Samantha Chan, Alex Cook and Pete Nicholls
