### ISSUE TITLE
Proposal for Internet of Things Foundation project/toolkit

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/administration#77]
The IBM Internet of Things (IoTF) service lets your apps communicate with and consume data collected by your connected devices, sensors, and gateways.

https://console.ng.bluemix.net/catalog/internet-of-things-foundation/

This project, `streamsx.iotf` would provide the ability to have an IBM Streams application easily interact with IoTF, either in Bluemix (Streaming Analytics Service) or on-premises (IBM Streams).

Basically the toolkit will initially provide data types and composites that map to the IoTF device model of events, commands and statuses, implementation will be basically wrappers around existing MQTT souce & sink operators, thus a Streams application would be accessing IoTF as a MQTT application.

Additional functional beyond the device model could be added in the future, such as generic device monitoring applications.

**Comment by mikespicer** [comment]
+1

**Comment by chanskw** [comment]
+1

Who should be the initial committers of this project?

**Comment by ddebrunner** [comment]
Initial committers @ddebrunner and @dlaboss

**Comment by leongor** [comment]
+1

**Comment by chanskw** [comment]
Created toolkit.  Also generated webpages.  Please let me know if you do not like the layout, we can always change it.

Thanks!

**Comment by ddebrunner** [comment]
Thanks!

**Comment by ddebrunner** [comment]
I

**Comment by chanskw** [comment]
are you having problem with writing to the repo?

**Comment by chanskw** [comment]
Can you please try again.... Github moved the button on me... so the repo was created as read-only by default.  But this should be fixed now.

**Comment by ddebrunner** [comment]
I just created a pull request but I don't see the button to merge it.

**Comment by ddebrunner** [comment]
Ok - that works. Thanks for the quick response!
