### ISSUE TITLE
Proposal for a new project: streamsx.jdbc

### ISSUE THREAD

**Issue by yiminy** [IBMStreams/administration#78]
I am proposing to have a new toolkit that supports Streams application to interact with database using JDBC.

JDBC is a Java database connectivity technology that defines how a client may access a database. The toolkit will allow you to run a user-defined SQL statement with JDBC driver that could have the following user scenarios:
1. Generate output stream from the result set of a SQL SELECT statement.
2. Insert, update and delete records, create and drop tables.
3. Call stored procedures.

**Comment by chanskw** [comment]
+1

**Comment by ddebrunner** [comment]
+1

**Comment by mikespicer** [comment]
+1

**Comment by chanskw** [comment]
To contribute, @yiminy please sign this agreement:
https://github.com/IBMStreams/administration/blob/master/IBMStreams-cla-individual.pdf

Please send a soft copy to myself and Pete Nicholls.  Please also send a hard copy to Pete.

Once this is done, then I will create a repository for you to contribute code.  Thanks!

**Comment by cancilla** [comment]
+1

**Comment by petenicholls** [comment]
+1

**Comment by leongor** [comment]
+1

**Comment by leongor** [comment]
+1

**Comment by chanskw** [comment]
@yiminy can you please tell me who are the committers to this project? 
Thanks!

**Comment by yiminy** [comment]
@chanskw, 
Ankit (@ankitpas) and myself will be the committers. Thanks...

**Comment by chanskw** [comment]
Created streamsx.jdbc
