### ISSUE TITLE
Add a template graduation status page?

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/administration#80]
Would it help to add a GRADUATION_STATUS.md to each project in incubation to help encourage progress towards graduation.

E.g. taking the list of items from this list: https://github.com/IBMStreams/administration/wiki/Project-Incubation-Process , something like:
- [x]  :white_check_mark: Stable release - **Multiple stable releases**
- [ ] :large_orange_diamond: Project is properly documented - **SPLDOC generated but few comments**
- [ ] :red_circle: Project has samples and instructions to help clients get started easily: **No samples!**

....

This project could have a template with the list of required items.

**Comment by chanskw** [comment]
+1 I think this is a great idea!

**Comment by leongor** [comment]
+1 like it very much!

**Comment by mikespicer** [comment]
+1

**Comment by chanskw** [comment]
Thanks @ddebrunner  for the contribution.

I have added this to all projects and opened issues for project committers to update with current status.

New projects created will also be populated with this page.
