### ISSUE TITLE
Proposal for new project streamsx.Solr

### ISSUE THREAD

**Issue by jjbosox** [IBMStreams/administration#82]
I am proposing creation of a new repository for integration with Apache Solr. 

“Solr is the popular, blazing-fast, open source enterprise search platform built on Apache Lucene”. Solr is extremely useful for text processing and searching. Search features for websites like StubHub and Zappos are powered by Solr. This toolkit would provide tight Streams integration with Solr features such as adding data, querying, word-stemming (lemmatization), and clustering. 
As a first step, we will add operators to add, update, delete, and query documents.

**Comment by Alex-Cook4** [comment]
+1 Makes sense to have Solr integration since we do a good amount of text processing with Streams.

**Comment by mikespicer** [comment]
+1

**Comment by chanskw** [comment]
+1

**Comment by chanskw** [comment]
Please advise on who I should put as committers to the project.
Please sign and mail a copy of this agreement to me and @petenicholls :
https://github.com/IBMStreams/administration/blob/master/IBMStreams-cla-individual.pdf

I will create the repository once I receive the signed agreement.

Thanks!

**Comment by chanskw** [comment]
@jjbosox  Please confirm if you have send the signed CLA and who else I should add as committer to this project?

Thanks!

**Comment by jjbosox** [comment]
The signed CLA has been sent.  Please make both Alex and I committer's to the project.

**Comment by chanskw** [comment]
Created streamsx.solr project.
