### ISSUE TITLE
Proposal  for new project streamsx.speech2text

### ISSUE THREAD

**Issue by jjbosox** [IBMStreams/administration#83]
I am proposing creation of a speech-to-text toolkit. 

Speech-to-text processing fits well into the Streams paradigm. Call-centers around the word are trying to leverage analytics on their phone calls ( audio ) to provide better service at a lower cost. 
This toolkit will provide integration with commonly used speech-to-text engines. This toolkit will also provide operators to help with load-management because of the performance intensity of speech-to-text translation. As a starting point, we will provide integration with Kaldi and Watson. Users will need to have Watson and/or Kaldi  installed on the systems to get the sample applications and operators to function properly. This toolkit  will not include IBM Watson IP.

**Comment by leongor** [comment]
I think it's a valuable addition to Streams - was thinking in this direction, but with Sphinx.
Kaldi as I understand provides no ready solution, but only tools to build one. What is the basic functionality you're going to introduce? Is it only English? Any text or fixed dictionary?
+1

**Comment by ddebrunner** [comment]
> This toolkit will also provide operators to help with load-management 

streamsx.plumbing has some load management operators. If these operators are not specific to speech contributing them to streamsx.plumbing would be appreciated.

**Comment by ddebrunner** [comment]
+1 
Will Watson integration include Watson services on Bluemix?

**Comment by mikespicer** [comment]
+1
Agree with @ddebrunner on load management operators being in streamsx.plumbing if they are to specific to speech.

**Comment by jjbosox** [comment]
@leongor  

I see no reason we could not include Sphinx it would simply be a matter of priorities . Kaldi does provide a nice ready solution but only for English.  A sleu of recipes exist such that other ready solutions are also available provided you have the corpus to work from .

@ddebrunner   

i will take a look at streamsx.plumbing . currently the operator mentioned is not generic in nature but its worth thinking about . 

At some point yes it would be well worth having integration with the Watson Services. our priorities right now however are to integrate with the code directly

**Comment by Alex-Cook4** [comment]
+1

**Comment by chanskw** [comment]
+1

**Comment by chanskw** [comment]
Please advise on who I should put as committers to the project.
Please sign and mail a copy of this agreement to me and @petenicholls :
https://github.com/IBMStreams/administration/blob/master/IBMStreams-cla-individual.pdf

I will create the repository once I receive the signed agreement.

Thanks!

**Comment by chanskw** [comment]
@jjbosox , please advise who the committers are, and if you have signed the CLA, so I can create the repository.

Thanks!

**Comment by chanskw** [comment]
created streamsx.speech2text.

Initial committer is @jjbosox
