### ISSUE TITLE
Proposal for new tutorial project tutorial.teda

### ISSUE THREAD

**Issue by m-kotowski** [IBMStreams/administration#84]
I propose to create a new tutorial project for the Telecommunications Event Data Analytics application framework, as discussed with Samantha.

The tutorial for the Telecommunications Event Data Analytics application framework is quite huge (approx. 10 chapters, each chapter having approx. 10 DIN A4 pages of text and graphics). The source documents (Word) that describe the creation of a complex mediation application using Stream Studio, shall be transferred to the project's wiki using Markdown styling. In addition, the same content shall be provided as downloadable Zeppelin Notebooks, which support semi-automated tasks (runnable Bash scripts) that lead to the same complex mediation application.

Due to the size, Samantha recommended to create a separate tutorial project.

**Comment by mikespicer** [comment]
+1

**Comment by chanskw** [comment]
+1

I suggest to name project:   streamsx.tutorial.teda

Any objection?

**Comment by chanskw** [comment]
Please advise on who I should put as committers to the project.
Please sign and mail a copy of this agreement to me and @petenicholls :
https://github.com/IBMStreams/administration/blob/master/IBMStreams-cla-individual.pdf

I will create the repository once I receive the signed agreement.

Thanks!

**Comment by m-kotowski** [comment]
Hi.
In a first step, please add the following colleagues:

- joergboe
- RolefH
- m-kotowski
- schulz2
- ZollnaPa

I already mailed the CLA for these colleagues one week ago to Pete. The signed papers I will send soon.

**Comment by chanskw** [comment]
Created repository.

I added the following as committers:
RolefH
m-kotowski
schulz2
ZollnaPa

Waiting for confirmation of CLA from @joergboe, and I will also add him as a committer.

Thanks!

**Comment by m-kotowski** [comment]
Please also add the following committers:

- brandtol
- golzto
- markheger
- GudrunKa
- rnostream

Thank you in advance.

**Comment by chanskw** [comment]
Done.. thanks!
