### ISSUE TITLE
Proposal new repository streamsx.mail

### ISSUE THREAD

**Issue by chanskw** [IBMStreams/administration#86]
I'd like to propose a new streamsx.mail repository.

The mail toolkit already exists on StreamsExchange:
https://www.ibm.com/developerworks/community/forums/html/topic?id=6385f52c-6f05-4702-a817-bd328ab6a00d

I'd like to move the toolkit over to Github and continue our development here.

**Comment by leongor** [comment]
+1

-----Original Message-----

**Comment by cancilla** [comment]
+1

**Comment by mikespicer** [comment]
+1

**Comment by chanskw** [comment]
Thanks!  Project created:  streamsx.mail

@jchailloux and myself are initial committers.

**Comment by ddebrunner** [comment]
SHould I assume that the approach described in #20 will not happen now?

**Comment by chanskw** [comment]
Sorry @ddebrunner I did not see #20. 

I'd like to propose that we do not put the mail operators into inet and have a separate mail toolkit.  In our experience so far, having a big toolkit with many operators tends to make it difficult to evolve the toolkit in the long run.  (e.g. messaging toolkit with operators dealing with many different servers). 

 It also increases the application bundle size when using these toolkits.  For example, if the mail operators are in the inet toolkit, an application needing the email function will need to include the inet toolkit in the application bundle.  This includes all dependencies that the inet toolkit include.  And in a lot cases, the extra jars required by the other operators are not needed by the application, as these other operators are not used.  This makes the bundle unnecessarily bigger.

**Comment by chanskw** [comment]
I will hold off delivering code to the new repository.  Please let me know if you disagree asap.

**Comment by ddebrunner** [comment]
Ok - I'll just close issue 33 in inet then, there was no progress on it anyway.

Thanks!
