### ISSUE TITLE
Proposal:  On-demand Toolkit Release Process

### ISSUE THREAD

**Issue by chanskw** [IBMStreams/administration#87]
In IBMStreams organization, toolkits projects are released on-demand.  

From the end-user perspective, it is hard to predict when a release will be available.  And if the user needs a release, there is no clear documented process on how to get a release to be published.

From the toolkit developer's perspective, there is no clear guidelines on what needs to be done to create a toolkit release.  For example, it is not always obvious that toolkit version numbers need to be updated upon a release.

I have started this process to try to clarify these two points:
- How would someone request for a build and what information is needed from the end-user?
- What is expected from the toolkit developer, when a release is to be made?

I also think it will be a good idea to start recording some of these in issues, so we can better keep track of branches, releases and history.

Please review the process and let me know what you think.

This is not a mandatory process.  It is up to the project owners to decide if they want to follow this process or not.  This is just a guideline.

https://github.com/IBMStreams/administration/wiki/On-Demand-Release-Process

**Comment by ddebrunner** [comment]
> Seek a +1 vote from at least one other committer

Somewhat in conflict with the graduation guidelines that state:

> Project must have at least one active committer

So a project can only have one committer and I think a few do, so there is no other committer to seek a vote from. But since it's up to project teams to follow the guidelines, since committer projects can do something else.

**Comment by chanskw** [comment]
Right, this is up to the project team to follow.
I think this process is more applicable to more mature project, where multiple committers are available.  For less mature project, the process can be tweaked.

**Comment by chanskw** [comment]
This is an example of how we implemented this process in streamsx.jdbc:
https://github.com/IBMStreams/streamsx.jdbc/issues/38

It helped us catch issues with bumping version numbers and testing is done and making sure that samples are ok.

**Comment by chanskw** [comment]
Closing this one, if you have more feedback on the process, please open new issues.
