### ISSUE TITLE
proposal for new toolkit: streamsx.opencv

### ISSUE THREAD

**Issue by ejpring** [IBMStreams/administration#88]
I'm updating the old 'OpenCV toolkit for Streams' to work with the current versions of FFmpeg, OpenCV, and Streams, and I'd like to move it from developerWorks to an IBMStreams repository named 'streamsx.opencv'.

**Comment by cancilla** [comment]
+1

**Comment by mikespicer** [comment]
+1 great to see this being updated and moved to github

**Comment by chanskw** [comment]
+1!

**Comment by ddebrunner** [comment]
+1

**Comment by leongor** [comment]
+1

2016-04-01 19:33 GMT+03:00 Dan Debrunner <notifications@github.com>:

> +1
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/IBMStreams/administration/issues/88#issuecomment-204461958>
>



-- 
Best regards,
Leonid Gorelik.

**Comment by chanskw** [comment]
Project created:  streamsx.opencv

@ejpring  is added as committer to project.
