### ISSUE TITLE
proposal for new toolkit: streamsx.shell

### ISSUE THREAD

**Issue by ejpring** [IBMStreams/administration#89]
I'm updating the old 'shell toolkit for Streams', and I'd like to move it from developerWorks to an IBMStreams repository named 'streamsx.shell'.

**Comment by ddebrunner** [comment]
What does it do?

**Comment by ejpring** [comment]
There are three operators: 

ShellSource executes an arbitrary Bash shell command (or pipeline of commands) and emits a tuple for each line written to STDOUT or STDERR.

ShellPipe executes a shell command, consumes lines from tuples and pipes them to the shell as STDIN, and emits a tuple for each line written to STDOUT or STDERR.

ShellSink executes a shell command, consumes tuples and pipes them to the shell as STDIN.

Each operator has an optional output port that emits a tuple with the exit code and some counters when the shell exits.

**Comment by ddebrunner** [comment]
+1

**Comment by leongor** [comment]
+1

2016-04-20 15:41 GMT+03:00 Dan Debrunner <notifications@github.com>:

> +1
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/IBMStreams/administration/issues/89#issuecomment-212407868>
>



-- 
Best regards,
Leonid Gorelik.

**Comment by chanskw** [comment]
+1

**Comment by cancilla** [comment]
+1

**Comment by mikespicer** [comment]
+1

**Comment by chanskw** [comment]
created streamsx.shell
