### ISSUE TITLE
[Proposal] Rename streamsx.iotf to streamsx.iot

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/administration#90]
streamsx.iotf is a toolkit that provides connectivity to IBM Watson IoT Platform (previously known as IoT Foundation) and extends its device model into SPL and Java for IBM Streams.

As the toolkit has evolved it's become clear to me that the device model is separate from the connectivity used to interact with devices. Similarly Apache Quarks has separated out the device model from the connectivity, so I'm proposing that this toolkit should be generalized to be an IoT (Internet of Things) toolkit, and not specific to IBM Watson IoT Platform, hence drop the (outdated) 'f' from the toolkit's name and packages.

The toolkit would provide:
* IoT Device model matching Apache Quarks
   * SPL/Java types and operators/functions that handle device events, commands etc.
   * Integration with Quarks' control mechanisms
* IBM Watson IoT Platform connectivity application (using com.ibm.streamsx.messaging)
* MQTT connectivity application (future work)  (using com.ibm.streamsx.messaging)
* Kafka connectivity application (future work)  (using com.ibm.streamsx.messaging)
* Sample applications

**Comment by ddebrunner** [comment]
Just to add the toolkit has only made pre-releases with version < 1.0 so I think it's ok to change the names etc. at this point in time, but before it gets to its first real 1.0 release.

**Comment by cancilla** [comment]
+1

**Comment by cancilla** [comment]
This may have been implied, but I'm guessing this means changing the toolkit name to "com.ibm.streamsx.iot"?

**Comment by chanskw** [comment]
+1

**Comment by mikespicer** [comment]
+1

**Comment by ddebrunner** [comment]
@cancilla Correct, I did say that:

`hence drop the (outdated) 'f' from the toolkit's name and packages.`

**Comment by ddebrunner** [comment]
I don't have permission to rename it, so once it's been agreed (already?) can one of the IBM Streams admins rename it. Thanks!

**Comment by chanskw** [comment]
done.  Please check

**Comment by ddebrunner** [comment]
Looks good, the gh-pages are also correctly renamed.

Thanks!
