### ISSUE TITLE
Proposal for new project: streamsx.weather

### ISSUE THREAD

**Issue by cancilla** [IBMStreams/administration#92]
# Introduction

The Bluemix **Insights for Weather** service allows users to retrieve historical and real-time weather data from The Weather Company. This data can enable applications to forecast and detect weather events. 

The service provides the following REST APIs for retrieving weather data: 

 * **Standard 1-Day Hourly** - An hourly weather forecast for the next 24 hours starting from the current time, for a specified geolocation
 * **Standard 10-Day Daily** - A daily forecast for each of the next 10 days starting from the current day, including forecasts for the daytime and nighttime segments.
 * **Current observations** - Observed weather data (temperature, wind direction and speed, humidity, pressure, dew point, visibility, and UV Index) that is collected from observation devices worldwide, plus a weather phrase and a matching weather icon.
 * **Historical data** - Observed weather data from site-based observation stations for a specified geolocation that includes current observations and up to 24 hours of past observations.

# Proposal 

I would like to propose that a new repository and toolkit be created for accessing data from the **Insights for Weather** service.

I propose that the repository be called **streamsx.weather** and that the toolkit be called **com.ibm.streamsx.weather**

# Initial contribution

The toolkit will initially contain the following Java operators for accessing each of the aforementioned REST APIs:

 * **CurrentWeather** operator
 * **ForecastDaily** operator 
 * **ForecastHourly** operator
 * **HistoricalWeather** operator

**Comment by leongor** [comment]
+1

2016-06-01 19:10 GMT+03:00 James Cancilla <notifications@github.com>:

> Introduction
>
> The Bluemix *Insights for Weather* service allows users to retrieve
> historical and real-time weather data from The Weather Company. This data
> can enable applications to forecast and detect weather events.
>
> The service provides the following REST APIs for retrieving weather data:
>
>    - *Standard 1-Day Hourly* - An hourly weather forecast for the next 24
>    hours starting from the current time, for a specified geolocation
>    - *Standard 10-Day Daily* - A daily forecast for each of the next 10
>    days starting from the current day, including forecasts for the daytime and
>    nighttime segments.
>    - *Current observations* - Observed weather data (temperature, wind
>    direction and speed, humidity, pressure, dew point, visibility, and UV
>    Index) that is collected from observation devices worldwide, plus a weather
>    phrase and a matching weather icon.
>    - *Historical data* - Observed weather data from site-based
>    observation stations for a specified geolocation that includes current
>    observations and up to 24 hours of past observations.
>
> Proposal
>
> I would like to propose that a new repository and toolkit be created for
> accessing data from the *Insights for Weather* service.
>
> I propose that the repository be called *streamsx.weather* and that the
> toolkit be called *com.ibm.streamsx.weather*
> Initial contribution
>
> The toolkit will initially contain the following Java operators for
> accessing each of the aforementioned REST APIs:
>
>    - *CurrentWeather* operator
>    - *ForecastDaily* operator
>    - *ForecastHourly* operator
>    - *HistoricalWeather* operator
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/IBMStreams/administration/issues/92>, or mute the
> thread
> <https://github.com/notifications/unsubscribe/AGvlA2WYx8SHrjM2c5htnjF7J2gWWrCvks5qHa8BgaJpZM4IruAD>
> .
>



-- 
Best regards,
Leonid Gorelik.

**Comment by chanskw** [comment]
+1!

**Comment by ddebrunner** [comment]
+100

**Comment by mikespicer** [comment]
+1

**Comment by YifatY** [comment]
+1

**Comment by chanskw** [comment]
Thanks everyone!  I have created the repository and contributed Jame's code.

Closing.
