### ISSUE TITLE
proposal: move 'streamsx.synchronize' toolkit from developerWorks to GitHub

### ISSUE THREAD

**Issue by ejpring** [IBMStreams/administration#95]
I'd like to move the 'streamsx.synchronize' toolkit from developerWorks ( see https://www.ibm.com/developerworks/community/files/app?lang=en#/file/5e390095-bf80-45b4-9308-16403a8a395c ) to GitHub. There's only one operator in the toolkit, named Synchronize:
 
The Synchronize operator synchronizes the flow of tuples through multiple streams according to timestamps in the tuples. Optionally, it can pace tuples faster or slower than they were originally produced, according to their timestamps.

**Comment by ddebrunner** [comment]
Looks like a candidate for streamsx.plumbing, rather than its own toolkit.

**Comment by ejpring** [comment]
Sure. I'll be happy to add Synchronize to 'streamsx.plumbing'.

**Comment by chanskw** [comment]
+1 to add to plumbing.  Please create pull request to streamsx.plumbing repository to have this moved.  Thanks!

**Comment by chanskw** [comment]
@ejpring I think you have already submitted a pull request to plumbing.  Closing this request.
