### ISSUE TITLE
Proposal: Project to support 'pip install' of Python code for IBM Streams

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/administration#97]
Project name: **IBMStreams/pypi.streamsx**

This is a step in allowing natural use of Streams for a Python developer.

A project that will be registered with PyPi to allow 'pip install' of Python packages that support Python developers interacting with IBM Streams. 'pip install' is the standard mechanism for Python developers to download code.
(See http://peterdowns.com/posts/first-time-with-pypi.html)

Project would initially support:

- Python Application API (from streamsx.topology)
- Python Rest API (from streamsx.utility)

Project would maintain copies of the files from other IBMStreams projects (or their releases), the master versions would remain in the source projects.

A single PyPi package for IBM Streams Python code is used rather than multiple to simplify setup for Python developers.

The name is `pypi.streamsx` to reflect it is a PyPi package containing the `streamsx` Python packages.
(`streamsx.pypi` might imply it's a SPL toolkit for interacting with PyPi).

**Comment by cancilla** [comment]
Yes! +1

**Comment by mikespicer** [comment]
+1

**Comment by wmarshall484** [comment]
+1

**Comment by ddebrunner** [comment]
Can this repo be created? Thanks!

**Comment by petenicholls** [comment]
Creating underway

**Comment by petenicholls** [comment]
done.
