### ISSUE TITLE
Proposal : WITSML toolkit

### ISSUE THREAD

**Issue by jchailloux** [IBMStreams/administration#98]
I created a prototype to access WITSML data thru webservice.
It could be nice to have it in order to start dealing with petroleum industry.

**Comment by mikespicer** [comment]
Hi Jerome, could you give a bit more background on WITSML and what the operators would be please.

**Comment by chanskw** [comment]
Hi, any update to this one?

**Comment by chanskw** [comment]
Any update here?  Are you still interested in contributing?

**Comment by chanskw** [comment]
Closing this one due to lack of activity.  Please reopen if you want to continue the discussion.  Thanks!
